option_hints = {
    all_out_war = "When enabled, every faction will be hostile to every other faction. When DrX's dynamic relations is detected, this wll only be applied at the beginning " ..
        "of a game.",

    random_starting_locations = "When enabled, the player will spawn at a random base in the zone. Every other base will be populated using the random_stalker_chance and " ..
        "random_mutant_chance options.",

    random_stalker_chance = "The chance, between 0 - 100, that stalker squads will be spawned at a base or resoruce point when random_starting_locations is enabled. " ..
        "This is the chance that a single squad will spawn. If a base has a max population of 2, and random_stalker_chance is set to 50, then there is a 50% chance that " ..
        "the first squad will spawn, and a 50% chance that the second squad will spawn.",

    random_monster_chance = "The chance, between 0 - 100, that mutant squads will be spawned at a territory point when random_starting_locations is enabled. Only one mutant " ..
        "per point will be spawned.",

    enable_auto_capture = "When enabled, the player will be able to capture points by standing within the distance specified by auto_capture_distance for the amount " ..
        "of time specified by auto_capture_time. If you are close to multiple points, the closest base will be chosen followed by the rest of the bases and then resource " ..
        "points; territory points are not auto-capturable",

    auto_capture_wait_time = "The amount of time, in in-game minutes, that it takes to capture a point manually.",

    auto_capture_max_distance = "Points within this distance to the player will be auto-captured; if the distance between the player and the point being captured is larger " ..
        "than this then it will stop being captured.",

    fog_of_war = "When enabled, anything within the fog_of_war_distance range to the player, or any squad of " ..
        "the same faction, will be shown. show_unfriendly_squads and hide_smarts will still affect whether or not an object is shown on the PDA.",

    fog_of_war_distance = "When fog_of_war is enabled, anything within this range to the player or any squad of the players faction will be shown on the PDA. " ..
        " show_unfriendly_squads and hide_smarts will still affect whether or not an object is shown on the PDA.",
        
    hide_unfriendly_squads = "When enabled, neutral and enemy squads will not be displayed on the PDA.",

    hide_smarts = "When enabled, smart terrain icons will not be rendered on the PDA. Targets of the player's faction will still be shown on the PDA.",

    hide_undergraund_smarts = "When enabled, underground smarts will be hidden from the PDA",
    
    enemy_new_game_bonus = "When enabled, enemy squads will have slightly more initial squads while neutral and friendly factions will have slightly less initial squads.",

    enemy_base_boost = "All enemies of the player's faction will be treated as if owning the specified number of bases in addition to what they really own.",
    
    enemy_resource_boost = "All enemies of the player faction will be treated as if owning the specified number of resources in addition to what they really own. " ..
        "Resources affect respawn time for defense / attack / patrol squads and how skilled the squads spawned are; higher resource count means faster respawn times with " ..
        "better squads.",

    actor_influence_weight = "How much priority each influence point adds to a target. Typical priority numbers are between 1 and 10; the higher the number the more " ..
        "likely points are to target the point with influence added to it.",

    actor_support_reward_influence = "Whenever you kill an enemy, you are rewarded this amount of influence points.",

    novice_squad_price = "The price of a novice squad. When you have this amount of money or more and right click a base of your own faction's, it will " ..
        "include an option to buy a novice squad which will be spawned at that base immediately and be treated as companions.",

    advanced_squad_price = "The price of an advanced squad. When you have this amount of money or more and right click a base of your own faction's, it will " ..
        "include an option to buy an advanced squad which will be spawned at that base immediately and be treated as companions.",

    veteran_squad_price = "The price of a veteran squad. When you have this amount of money or more and right click a base of your own faction's, it will " ..
        "include an option to buy a veteran squad which will be spawned at that base immediately and be treated as companions.",

    heli_price = "The price of a helicopter. When you have this amount of money or more and right click a base of your own faction's, it will " ..
        "include an option to buy a helicopter. There can only be one helicopter per-faction on a single level.",

    actor_support_enemy_rank_weight = "When you kill an enemy, you will be rewarrded actor_support_reward_money + (enemy_rank * actor_support_enemy_rank_weight)",

    actor_support_reward_money = "When you kill an enemy, you will be rewarrded actor_support_reward_money + (enemy_rank * actor_support_enemy_rank_weight)",

    monster_max_squads_per_level = "Whenever there is less than this amount of mutant squads on a level, the level will be able to be targeted by other mutant squads and " ..
        "mutants will spawn at any unoccupied point or lair based on the monster_min_faction_respawn and monster_max_faction_respawn variables",

    monster_min_faction_respawn = "The minimum amount of time that passes before a lair or unoccupied base/resource spawns a mutant squad if there are less than " ..
        "monster_max_squads_per_level mutant squads already on the point's level.",

    monster_max_faction_respawn = "The maximum amount of time that passes before a lair or unoccupied base/resource spawns a mutant squad if there are less than " ..
        "monster_max_squads_per_level mutant squads already on the point's level.",

    zombies_act_as_faction = "When enabled, zombified stalkers will take part in the faction wars.",

    disable_offline_combat = "When enabled, squads will not participate in offline combat. This will, in effect, cause warfare to set up battles that will unfold " .. 
        "as you approach them. This will slow warfare down and make it center around you and the squads around you.",

    simulate_offline_combat_at_smarts = "When enabled, squads will only simulate offline combat when they are defending a target point. If two squads are near by " .. 
        "but waiting at different smart terrains, they will not engage in offline combat.",

    enable_mutant_offline_combat = "When enabled, mutants will participate in offline combat. When disabled, mutants will have a more notable presence in the zone.",

    enable_offline_news = "When enabled, you will receive offline news updates whenever a friendly squads enter offline combat, enter online combat, or a base is " ..
        "taken/lost by/from a friendly faction",

    offline_news_display_percentage = "A number between 0 and 100; Warfare will only display this percentage of offline news messages.",

    disable_smart_pop_cap = "When enabled, smart terrains will not auto-remove overflow squads.",

    debug_logging = "When enabled, Warfare will use debug logging. Debug logging will log the beginning and end of most functions in warfare, so it will " ..
        "inflate your log size quite a bit.",

    min_faction_respawn = "The minimum amount of time that must pass for a base to spawn a defense squad. This along with the base's available resources determines the " ..
        "bases defense respawn time. A base's available resources is determined by the following: total_resources = global_resources + (regional_resources * 2) + " ..
        "(local_resources * 3). The base's respawn time is determined by choosing a value between the mininum and maximum faction respawn time with a factor of " ..
        "resource_count / warfare.resource_count. respawn time = (100% - owned_resource_percentage) * min_faction_respawn + (owned_resource_percentage * max_faction_respawn ",

    max_faction_respawn = "The maximum amount of time that must pass for a base to spawn a defense squad. This along with the base's available resources determines the " ..
        "bases defense respawn time. A base's available resources is determined by the following: total_resources = global_resources + (regional_resources * 2) + " ..
        "(local_resources * 3). The base's respawn time is determined by choosing a value between min_faction_respawn and max_faction_respawn with a factor of " ..
        "resource_count / warfare.resource_count. respawn time = (100% - owned_resource_percentage) * min_faction_respawn + (owned_resource_percentage * max_faction_respawn ",

    min_invasion_size = "The minimum invasion size multiplier. This is used along with max_invasion_size and the number of bases the faction owns in order to " ..
        "calculate a final invasion_size. This is a multiplier for a smart terrains max_population, so the stalker population factor from the stalker gameplay options " ..
        "will affect the final invasion size. Current invasion size = (100% - owned_base_percentage) * min_invasion_size + (owned_base_percentage * max_invasion_size). " ..
        "Current invasion population = min(1, target.max_population * Current invasion size)",

    max_invasion_size = "The maximum invasion size multiplier. This is used along with max_invasion_size and the number of bases the faction owns in order to " ..
        "calculate a final invasion_size. This is a multiplier for a smart terrains max_population, so the stalker population factor from the stalker gameplay options " ..
        "will affect the final invasion size. Current invasion size = (100% - owned_base_percentage) * min_invasion_size + (owned_base_percentage * max_invasion_size). " ..
        "Current invasion population = min(1, target.max_population * Current invasion size)",

    invasion_departure_chance = "The chance that an invasion will depart during the current process_targets update. This is called every 1 to 5 in-game minutes.",

    min_patrol_squads = "The minimum patrol squad population factor. When a faction owns no bases, each base would (theoretically since they don't own any) have " ..
        "min_patrol_squads * max_population amount of patrol squads. Current patrol squad factor = (100% - owned_base_percentage) * min_patrol_squds + (owned_base_percentage * max_patrol_squads. " ..
        "Current allowed patrols quads = base.max_population * current patrol squad factor.",

    max_patrol_squads = "The maximum patrol squad population factor. When a faction owns every base, each base will have " ..
        "max_patrol_squads * max_population amount of patrol squads. Current patrol squad factor = (100% - owned_base_percentage) * min_patrol_squds + (owned_base_percentage * max_patrol_squads. " ..
        "Current allowed patrols quads = base.max_population * current patrol squad factor.",

    min_patrol_time = "The minimum amount of time that must pass for a base to spawn a patrol squad. This along with the base's available resources determines the " ..
        "bases patrol respawn time. A base's available resources is determined by the following: total_resources = global_resources + (regional_resources * 2) + " ..
        "(local_resources * 3). The base's patrol respawn time is determined by choosing a value between min_patrol_time and max_patrol_time with a factor of " ..
        "resource_count / warfare.resource_count. respawn time = (100% - owned_resource_percentage) * min_patrol_time + (owned_resource_percentage * max_patrol_time ",

    max_patrol_time = "The maximum amount of time that must pass for a base to spawn a patrol squad. This along with the base's available resources determines the " ..
        "bases patrol respawn time. A base's available resources is determined by the following: total_resources = global_resources + (regional_resources * 2) + " ..
        "(local_resources * 3). The base's patrol respawn time is determined by choosing a value between min_patrol_time and max_patrol_time with a factor of " ..
        "resource_count / warfare.resource_count. respawn time = (100% - owned_resource_percentage) * min_patrol_time + (owned_resource_percentage * max_patrol_time ",

    min_patrol_rest_time = "The minimum amount of time a patrol squad will wait at a territory point. Night activity chance will also affect whether or not they are " ..
        "sent to a new territory point",

    max_patrol_rest_time = "The maximum amount of time a patrol squad will wait at a territory point. Night activity chance will also affect whether or not they are " ..
        "sent to a new territory point",

    offline_power_multiplier = "When a squad deals damage in offline combat, it is multiplied by this amount. If this is set to 2, for instance, squads that are a part " ..
        "of this faction will deal twice as much damage as typical squads in offline combat.",

    expansion_aggression = "Every time a base has less than the allowed number of targets and process_targets is called, a random number will be generated between 0 and 100. " ..
        "If this number is less than or equal to the expansion_aggression, the faction will choose a new target. Otherwise, the faction will not choose any new targets.",

    night_activity_chance = "The chance that a faction will send out invasion forces or send patrol squads anywhere during the night time. Night time is considered as between " ..
        "the hours of 8:00pm and 6:00am, or 20:00 and 6:00",

    base_priority = "How much the faction prioritizes bases. Typical priority numbers are between 0 and 10.",

    resource_priority = "How much the faction prioritizes resource points. Typical priority numbers are between 0 and 10.",

    territory_priority = "How much the faction prioritizes territory points. Typical priority numbers are between 0 and 10.",

    flag_priority = "How much a base prioritizes points that are flagged for their owning faction in the gamedata/configs/misc/simulation_objects_props.ltx file. For instance "..
        "if Clear Sky is looking at a territory piont, it will increase the priority for a point by 2 if in that file the point has csky = 1 defined for it. ",

    is_being_targeted_priority = "If a base is being targeted by another base, it will add this much priority to it in order to attempt to counter the invasion.",

    target_weaker_priority = "How much a base prioritizes points which have less powerful squads present.",

    target_stronger_priority = "How much a base prioritizes points which have more powerful squads present.",

    target_on_same_level_priority = "How much a base prioritizes points which are on the same level as itself.",
    
    max_smart_targets_per_base = "How many points a base can target at once.",

    resource_count_modifier = "How many resource points are added to each base's available resource points. This can be negative. Higher numbers cause faster respawn times.",

    base_count_modifier = "How many bases are added to each faction's owned base count. This can be negative. Higher numbers cause more patrols and larger invasion forces.",

    random_squad_count = "When enabled, every squad for this faction will have a random number of NPCs between min_random_squad_count and max_random_squad_count.",

    min_random_squad_count = "When random_squad_count is enabled, this is the minimum number of NPCs a squad will have for this faction.",

    max_random_squad_count = "When random_squad_count is enabled, this is the maximum number of NPCs a squad will have for this faction.",

    patrol_hunt_chance = "When a base is looking for a new target for a patrol squad, and if there is an enemy patrol squad on the current level or a linked level, " ..
        "this is the chance that the base will assign the enemy patrol squad as a target; if the squad is not assigned an enemy patrol squad as a target " ..
        "then it will be assigned a territory point near the base to patrol as usual.",

    random_starting_character = "When this option is enabled it will randomize the name and faction of the player after starting a new game; best used " ..
        "with random_starting_locations."
}